version: '3'
services:
    php:
        build:
            context: ./docker/php
        volumes:
            - ./src/my-app:/var/www
    nginx:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./src/my-app:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    mysql:
        image: mysql:5.7.22
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_DATABASE: test
        volumes:
            - ./docker/mysql:/var/lib/mysql
        ports:
            - 3306:3306
